name: CI

on: [push, pull_request]

jobs:
  # build:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Get Conan
  #       id: conan
  #       uses: ./ # Uses an action in the root directory

  #     - name: Did we get Conan?
  #       run: echo "Conan version was '${{ steps.conan.outputs.version }}'"

  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get Chalet
        uses: dimitre/get-chalet@v1
      - name: Is this love?
        shell: bash
        run: |
          cd chalet
          ./chalet --version