name: ChaletTest

on: [push, pull_request]

jobs:
  # build:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Get Conan
  #       id: conan
  #       uses: ./ # Uses an action in the root directory

  #     - name: Did we get Conan?
  #       run: echo "Conan version was '${{ steps.conan.outputs.version }}'"

  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get Chalet
        uses: dimitre/get-chalet@v2
      - name: Is this love?
        shell: bash
        run: |
          ./chalet/build/**/chalet --version
          # if [ "$RUNNER_OS" == "macOs" ]; then
          #   cd chalet/build/x86_64-apple-darwin_Release
          # elif [ "$RUNNER_OS" == "Linux" ]; then
          #   cd chalet/build/x86_64-apple-darwin_Release
          # fi
          # ./chalet --version

